# hypridle configuration
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hypridle

general {
    after_sleep_cmd = hyprctl dpms on
    ignore_dbus_inhibit = false
    lock_cmd = hyprlock
}

# Lock the screen after 10 minutes of inactivity
listener {
    timeout = 600
    on-timeout = hyprlock
}

# Turn displays off after 15 minutes of inactivity
listener {
    timeout = 900
    on-timeout = hyprctl dpms off
    on-resume = hyprctl dpms on
}

# Lock ~10s before system goes to sleep
listener {
    timeout = 10
    on-sleep = hyprlock
}